version: '3'

services:
  app:
    build: .
    ports:
     - "8000:8000"
    volumes:
     - .:/usr/src/app
  selenium:
    image: selenium/standalone-chrome
    shm_size: "2gb"
    ports:
      - "4444:4444"
      - "5900:5900"